/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.todolist.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Todolist service. Represents a row in the &quot;todo_Todolist&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.todolist.model.impl.TodolistModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.todolist.model.impl.TodolistImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Todolist
 * @generated
 */
@ProviderType
public interface TodolistModel extends BaseModel<Todolist> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a todolist model instance should use the {@link Todolist} interface instead.
	 */

	/**
	 * Returns the primary key of this todolist.
	 *
	 * @return the primary key of this todolist
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this todolist.
	 *
	 * @param primaryKey the primary key of this todolist
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the task ID of this todolist.
	 *
	 * @return the task ID of this todolist
	 */
	public long getTaskId();

	/**
	 * Sets the task ID of this todolist.
	 *
	 * @param taskId the task ID of this todolist
	 */
	public void setTaskId(long taskId);

	/**
	 * Returns the group ID of this todolist.
	 *
	 * @return the group ID of this todolist
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this todolist.
	 *
	 * @param groupId the group ID of this todolist
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the ID of this todolist.
	 *
	 * @return the ID of this todolist
	 */
	public long getId();

	/**
	 * Sets the ID of this todolist.
	 *
	 * @param Id the ID of this todolist
	 */
	public void setId(long Id);

	/**
	 * Returns the createdby of this todolist.
	 *
	 * @return the createdby of this todolist
	 */
	public long getCreatedby();

	/**
	 * Sets the createdby of this todolist.
	 *
	 * @param createdby the createdby of this todolist
	 */
	public void setCreatedby(long createdby);

	/**
	 * Returns the modifiedby of this todolist.
	 *
	 * @return the modifiedby of this todolist
	 */
	@AutoEscape
	public String getModifiedby();

	/**
	 * Sets the modifiedby of this todolist.
	 *
	 * @param modifiedby the modifiedby of this todolist
	 */
	public void setModifiedby(String modifiedby);

	/**
	 * Returns the create date of this todolist.
	 *
	 * @return the create date of this todolist
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this todolist.
	 *
	 * @param createDate the create date of this todolist
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this todolist.
	 *
	 * @return the modified date of this todolist
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this todolist.
	 *
	 * @param modifiedDate the modified date of this todolist
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the enrollment no of this todolist.
	 *
	 * @return the enrollment no of this todolist
	 */
	@AutoEscape
	public String getEnrollmentNo();

	/**
	 * Sets the enrollment no of this todolist.
	 *
	 * @param enrollmentNo the enrollment no of this todolist
	 */
	public void setEnrollmentNo(String enrollmentNo);

	/**
	 * Returns the first name of this todolist.
	 *
	 * @return the first name of this todolist
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this todolist.
	 *
	 * @param firstName the first name of this todolist
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the description of this todolist.
	 *
	 * @return the description of this todolist
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this todolist.
	 *
	 * @param description the description of this todolist
	 */
	public void setDescription(String description);

	/**
	 * Returns the status of this todolist.
	 *
	 * @return the status of this todolist
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this todolist.
	 *
	 * @param status the status of this todolist
	 */
	public void setStatus(String status);

	/**
	 * Returns the tags of this todolist.
	 *
	 * @return the tags of this todolist
	 */
	@AutoEscape
	public String getTags();

	/**
	 * Sets the tags of this todolist.
	 *
	 * @param tags the tags of this todolist
	 */
	public void setTags(String tags);

}